'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, CheckCircle2, ChevronLeft, Clock3, ShieldCheck, Wrench } from 'lucide-react';
const key='foodsaf365_phase1';
function load(){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
function save(v:any){localStorage.setItem(key,JSON.stringify(v));window.dispatchEvent(new Event('foodsaf365:update'));}
function label(s:string){return s==='awaiting_verification'?'Awaiting verification':s==='in_progress'?'In progress':s==='closed'?'Closed':'Open'}
export default function ActionsPage(){const [d,setD]=useState<any>({});const [tab,setTab]=useState('all');useEffect(()=>{const r=()=>setD(load());r();window.addEventListener('foodsaf365:update',r);return()=>window.removeEventListener('foodsaf365:update',r)},[]);const actions=d.actions||[];const shown=useMemo(()=>tab==='all'?actions:actions.filter((a:any)=>a.status===tab),[actions,tab]);return <main><div className="topbar"><div className="brand">FoodSafe365</div><div className="muted">ABC Restaurant · Action Centre</div></div><div className="container"><div className="checks-nav"><Link href="/manager" className="muted nav-link"><ChevronLeft size={18}/> Manager review</Link><span className="muted">Restaurant actions</span></div><div className="checks-header"><div><p className="eyebrow">ALERT → ACTION</p><h1>Restaurant Actions</h1><p className="muted">Every action here comes from a manager-reviewed food-safety alert.</p></div><div className="check-progress-box"><strong>{actions.filter((a:any)=>a.status!=='closed').length}</strong><span className="muted">open actions</span></div></div><div className="tabs">{[['all','All'],['open','Open'],['in_progress','In progress'],['awaiting_verification','Awaiting verification'],['closed','Closed']].map(([v,l])=><button key={v} className={tab===v?'tab active':'tab'} onClick={()=>setTab(v)}>{l}</button>)}</div>{shown.length===0?<div className="card empty-state"><CheckCircle2/><div><strong>No actions in this view</strong><p className="muted">A manager-reviewed alert will create a restaurant action.</p></div></div>:<div className="action-list">{shown.map((a:any)=><Link href={`/actions/${a.id}`} className="card action-row" key={a.id}><div className="icon-tile danger"><Wrench/></div><div className="action-row-main"><div className="action-row-top"><h3>{a.title}</h3><span className="pill attention">{label(a.status)}</span></div><p className="muted">{a.description}</p><div className="action-meta"><span><Clock3 size={15}/> Created {new Date(a.createdAt).toLocaleDateString()}</span><span><ShieldCheck size={15}/> Manager reviewed alert</span></div></div><ChevronLeft className="action-chevron" size={20}/></Link>)}</div>}</div></main>}
