'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import { ClipboardCheck, FileText, History, ShieldCheck, ChevronLeft, Loader2, CheckCircle2, AlertTriangle, Wrench, Thermometer } from 'lucide-react';
import { apiFetch } from '@/lib/api';
type RecordData={outlet:{name:string};monitoring?:Array<{id:string;ccpId:string;observedValue:number;unit:string;withinLimit:boolean;observationTime:string;actionRequired:boolean;correctiveActionId?:string|null}>;checks:Array<{id:string;date:string;area:string;template:string;result:string;issues:number}>;actions:Array<any>;timeline:Array<{id:string;at:string;type:string;detail:string;status:string}>;summary:{checksRecorded:number;issues:number;openActions:number;closedActions:number}};
const fmt=(v:string)=>new Date(v).toLocaleString([], {day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
const statusLabel=(s:string)=>s==='closed'?'Closed':s==='awaiting_verification'?'Awaiting verification':s==='open'?'Open':s.replace('_',' ');
export default function Records(){
 const [d,setD]=useState<RecordData|null>(null); const [tab,setTab]=useState('checks'); const [error,setError]=useState('');
 useEffect(()=>{apiFetch<RecordData>('/records').then(setD).catch(e=>setError(e.message||'Unable to load records.'));},[]);
 if(!d)return <main><div className="container"><Loader2 className="spin"/><p className="muted">Loading records…</p>{error&&<p className="error">{error}</p>}</div></main>;
 return <main><div className="topbar"><div className="brand">FoodSafe365</div><div className="muted">{d.outlet.name} · Manager</div></div><div className="container">
  <div className="checks-nav"><Link href="/home" className="muted nav-link"><ChevronLeft size={18}/> Home</Link></div>
  <div className="checks-header"><div><p className="eyebrow">RECORDS & HISTORY</p><h1>Records</h1><p className="muted">A traceable history of checks, issues, corrections and verification.</p></div><div className="check-progress-box"><strong>{d.summary.checksRecorded}</strong><span className="muted">checks recorded</span></div></div>
  <div className="grid grid3 record-summary"><div className="card metric-card"><ClipboardCheck/><span>Checks recorded</span><strong>{d.summary.checksRecorded}</strong></div><div className="card metric-card"><Wrench/><span>Open actions</span><strong>{d.summary.openActions}</strong></div><div className="card metric-card"><ShieldCheck/><span>Closed actions</span><strong>{d.summary.closedActions}</strong></div></div>
  <div className="tabs record-tabs"><button className={`tab ${tab==='checks'?'active':''}`} onClick={()=>setTab('checks')}>Daily checks</button><button className={`tab ${tab==='actions'?'active':''}`} onClick={()=>setTab('actions')}>Corrective actions</button><button className={`tab ${tab==='monitoring'?'active':''}`} onClick={()=>setTab('monitoring')}>HACCP monitoring</button><button className={`tab ${tab==='timeline'?'active':''}`} onClick={()=>setTab('timeline')}>Audit trail</button></div>
  {tab==='checks'&&<section><div className="section-title"><h2>Daily check history</h2><span className="muted">Recent records</span></div><div className="record-list">{d.checks.map(c=><div className="card record-row" key={c.id}><div className="record-icon"><ClipboardCheck/></div><div className="record-main"><div className="record-title"><strong>{c.template}</strong><span className={`pill ${c.result==='good'?'good':'attention'}`}>{c.result==='good'?'Good':'Needs attention'}</span></div><p className="muted">{c.area} · {c.date}</p></div><div className="record-end">{c.issues>0?<><AlertTriangle size={16}/>{c.issues} issue</>:<><CheckCircle2 size={16}/>No issues</>}</div></div>)}</div></section>}
  {tab==='monitoring'&&<section><div className="section-title"><h2>HACCP monitoring history</h2><Link href="/haccp" className="btn secondary">Open HACCP Plan</Link></div>{(d.monitoring||[]).length===0?<div className="card"><p className="muted">No CCP monitoring records yet.</p></div>:<div className="record-list">{(d.monitoring||[]).map((m:any)=><div className="card record-row" key={m.id}><div className="record-icon"><Thermometer/></div><div className="record-main"><div className="record-title"><strong>{m.ccpId==='ccp-1'?'Cooking':'CCP monitoring'}</strong><span className={`pill ${m.withinLimit?'good':'action'}`}>{m.withinLimit?'Within limit':'Deviation'}</span></div><p className="muted">{m.observedValue} {m.unit} · {fmt(m.observationTime)}</p></div><div className="record-end">{m.correctiveActionId?<Link href={`/actions/${m.correctiveActionId}`} className="nav-link">View action</Link>:<span className="muted">No action</span>}</div></div>)}</div>}</section>}
  {tab==='actions'&&<section><div className="section-title"><h2>Corrective-action history</h2><Link href="/actions" className="btn secondary">Open Actions Centre</Link></div><div className="record-list">{d.actions.map((a:any)=><Link href={`/actions/${a.id}`} className="card record-row record-link" key={a.id}><div className="record-icon"><Wrench/></div><div className="record-main"><div className="record-title"><strong>{a.title}</strong><span className={`pill ${a.status==='closed'?'good':a.priority==='high'?'danger':'attention'}`}>{statusLabel(a.status)}</span></div><p className="muted">Priority {a.priority} · Due {a.dueDate||'—'}</p></div></Link>)}</div></section>}
  {tab==='timeline'&&<section><div className="section-title"><h2>Audit trail</h2><span className="muted">Traceable activity</span></div><div className="timeline">{d.timeline.map(e=><div className="card timeline-row" key={e.id}><div className="timeline-dot"><History/></div><div><strong>{e.type}</strong><p>{e.detail}</p><small className="muted">{fmt(e.at)}</small></div></div>)}</div><div className="notice info-notice"><FileText size={18}/><span>Future releases will add downloadable inspection-ready reports and document/evidence indexing. This screen is the operational history layer.</span></div></section>}
  <div className="action-bar"><Link href="/home" className="btn secondary">Back to Home</Link><button className="btn secondary" onClick={()=>location.reload()}>Refresh</button></div>
 </div></main>}
