export type DemoHazard = { id:string; processStep:string; hazardType:'biological'|'chemical'|'physical'|'allergen'; description:string; likelihood:number; severity:number; riskScore:number; controlMeasure:string; significant:boolean };
export type DemoCCP = { id:string; hazardId:string; processStep:string; justification:string; criticalLimit:string; unit:string; monitoringMethod:string; monitoringFrequency:string; responsibleRole:string; correctiveAction:string; verificationMethod:string; fssaiReference?:string; fssaiSource?:string; criticalLimitMin?:number; criticalLimitMax?:number; validationStatus?:'validated'|'pending'; };
export type DemoPlan = { id:string; outletId:string; name:string; version:string; status:'draft'|'active'|'superseded'|'archived'; effectiveFrom:string; reviewDate:string; hazards:DemoHazard[]; ccps:DemoCCP[]; updatedAt:string };
const plans=new Map<string,DemoPlan>(); const today=()=>new Date().toISOString().slice(0,10);
function seed():DemoPlan{const hazards:DemoHazard[]=[
{id:'haz-1',processStep:'Receiving',hazardType:'biological',description:'Unsafe or contaminated incoming food.',likelihood:3,severity:4,riskScore:12,controlMeasure:'Approved suppliers, receiving inspection and temperature/condition checks where applicable.',significant:true},
{id:'haz-2',processStep:'Refrigerated storage',hazardType:'biological',description:'Growth of pathogens from inadequate storage control.',likelihood:3,severity:4,riskScore:12,controlMeasure:'Validated storage criteria, monitoring, stock rotation and corrective action.',significant:true},
{id:'haz-3',processStep:'Preparation',hazardType:'biological',description:'Cross-contamination between raw and ready-to-eat foods.',likelihood:3,severity:4,riskScore:12,controlMeasure:'Segregation, hand hygiene, cleaned equipment and controlled workflow.',significant:true},
{id:'haz-4',processStep:'Cooking',hazardType:'biological',description:'Survival of relevant biological hazards if the process is inadequate.',likelihood:3,severity:5,riskScore:15,controlMeasure:'Validated cooking process with defined monitoring and corrective action.',significant:true},
{id:'haz-5',processStep:'Cooling cooked food',hazardType:'biological',description:'Growth of pathogens during cooling.',likelihood:3,severity:5,riskScore:15,controlMeasure:'Validated cooling process, monitoring and defined corrective action.',significant:true},
{id:'haz-6',processStep:'Reheating',hazardType:'biological',description:'Survival/growth of hazards if reheating is inadequate or delayed.',likelihood:2,severity:5,riskScore:10,controlMeasure:'Validated reheating process and monitoring.',significant:true},
{id:'haz-7',processStep:'Packaging / service',hazardType:'physical',description:'Foreign material contamination.',likelihood:2,severity:3,riskScore:6,controlMeasure:'Packaging inspection, hygienic handling and controlled service area.',significant:false}];
const ccps:DemoCCP[]=[
{id:'ccp-1',hazardId:'haz-4',processStep:'Cooking',justification:'Potential CCP — confirm with the HACCP decision process for the specific food/process.',criticalLimit:'Enter the validated product/process-specific critical limit.',unit:'',criticalLimitMin:undefined,criticalLimitMax:undefined,validationStatus:undefined,fssaiReference:'FSSAI reference: cooking criteria depend on food type and validated process. For example, FSSAI hygiene-rating criteria cite vegetarian cooking at 60°C for 10 min or 65°C for 2 min core; non-vegetarian at 65°C for 10 min, 70°C for 2 min or 75°C for 15 sec core.',fssaiSource:'https://hygiene.fssai.gov.in/',monitoringMethod:'Measure the validated core/process parameter at the defined point using a suitable calibrated device.',monitoringFrequency:'As defined in the validated process.',responsibleRole:'Food Safety Supervisor',correctiveAction:'Hold affected food, assess disposition and restore control according to the approved procedure.',verificationMethod:'Review monitoring records and periodically verify the process and measuring device.'},
{id:'ccp-2',hazardId:'haz-5',processStep:'Cooling cooked food',justification:'Potential CCP — confirm through hazard analysis and the decision process.',criticalLimit:'Enter the validated product/process-specific cooling limit.',unit:'',criticalLimitMin:undefined,criticalLimitMax:undefined,validationStatus:undefined,fssaiReference:'FSSAI hygiene-rating reference: high-risk cooked food for refrigeration is cooled from 60°C to 21°C within 2 hours or less and then to 5°C within a further 2 hours or less. Use the outlet\'s approved/validated HACCP process as the control reference.',fssaiSource:'https://hygiene.fssai.gov.in/',monitoringMethod:'Measure and record the validated cooling temperature at defined time points (for example, start, 21°C checkpoint and final chilled checkpoint).',monitoringFrequency:'As defined in the validated process.',responsibleRole:'Food Safety Supervisor',correctiveAction:'Segregate affected food and follow the approved disposition/corrective-action procedure.',verificationMethod:'Review records, trend deviations and verify the cooling process periodically.'}];
return {id:'demo-haccp',outletId:'demo-outlet',name:'ABC Restaurant Food Safety Plan',version:'1.0',status:'draft',effectiveFrom:today(),reviewDate:new Date(Date.now()+90*86400000).toISOString().slice(0,10),hazards,ccps,updatedAt:new Date().toISOString()};}
export function getDemoPlan(){if(!plans.has('demo-haccp'))plans.set('demo-haccp',seed());return plans.get('demo-haccp')!;}
export function updateDemoPlan(patch:Partial<DemoPlan>){const p=getDemoPlan();const n={...p,...patch,updatedAt:new Date().toISOString()};plans.set(p.id,n);return n;}
