export type FoodSafeCheck = {
 id:number; code:string; category:string; title:string; frequency:'Opening'|'Daily'|'Per shift'|'Process'|'As applicable'; input:'yes_no'|'temperature';
 why:string; what:string[]; standard:string; risk:string; action:string;
};

export const FOODSAFE28: FoodSafeCheck[] = [
 {id:1,code:'FS28-01',category:'Premises & environment',title:'Food preparation areas are clean and orderly',frequency:'Opening',input:'yes_no',why:'Clean preparation areas reduce the chance that dirt, residues or other contaminants reach food.',what:['Look at counters, work tables, floors and food-preparation areas.','Check that food is protected while cleaning is carried out.'],standard:'Food premises and food-contact areas should be kept clean, maintained and suitable for food operations.',risk:'Residues and contaminated surfaces can transfer contamination to food.',action:'Stop the affected activity, clean the area and re-check before continuing.'},
 {id:2,code:'FS28-02',category:'Premises & environment',title:'No standing water in food areas',frequency:'Opening',input:'yes_no',why:'Standing water can support microbial growth and attract pests.',what:['Look around floors, drains, sinks and equipment.','Report leaks, blocked drains or water accumulation.'],standard:'Food-handling areas should not have stagnant water; drainage should be adequate.',risk:'Water accumulation can create hygiene and pest problems.',action:'Remove the water and report the source of leakage or drainage problem.'},
 {id:3,code:'FS28-03',category:'Premises & environment',title:'Drains are clean and functioning',frequency:'Daily',input:'yes_no',why:'Blocked or dirty drains can become a source of contamination and pest activity.',what:['Check that drains flow freely.','Look for food/grease build-up and unpleasant accumulation.'],standard:'Drains should handle expected flow and be maintained hygienically with appropriate traps.',risk:'Poor drainage can cause contamination, odour and pest activity.',action:'Clean/clear the drain as permitted and raise maintenance or pest-control follow-up when needed.'},
 {id:4,code:'FS28-04',category:'Premises & environment',title:'Doors, windows and barriers prevent pest entry',frequency:'Opening',input:'yes_no',why:'Pests need an entry route. Keeping barriers intact reduces the opportunity for infestation.',what:['Check doors, windows, screens and other openings.','Look for gaps or damaged screens.'],standard:'Potential pest entry points should be protected or controlled.',risk:'Pests can contaminate food, equipment and food-contact surfaces.',action:'Close/protect the entry point and create a maintenance or pest-control issue if it cannot be corrected immediately.'},
 {id:5,code:'FS28-05',category:'Personal hygiene',title:'Hands are washed at required times',frequency:'Per shift',input:'yes_no',why:'Hands can transfer microorganisms directly to food and food-contact surfaces.',what:['Observe handwashing before food handling and after contamination risks.','Check that staff do not substitute unsafe practices for handwashing.'],standard:'Food handlers should maintain personal hygiene and wash hands appropriately before and during food handling.',risk:'Poor hand hygiene can transfer contamination to ready-to-eat food.',action:'Stop the unsafe practice, wash hands correctly and reinforce the required handwashing point.'},
 {id:6,code:'FS28-06',category:'Personal hygiene',title:'Hand-washing station has water and soap',frequency:'Opening',input:'yes_no',why:'Food handlers cannot wash their hands correctly if the facility is not ready.',what:['Check water supply, soap and the handwashing facility.','Ensure the station is accessible and not blocked.'],standard:'Handwashing facilities should be provided with the necessary supplies.',risk:'Missing supplies can make required hygiene practices impractical.',action:'Restore the supply immediately and report recurring shortages.'},
 {id:7,code:'FS28-07',category:'Personal hygiene',title:'Clean protective clothing and head covering are used where required',frequency:'Per shift',input:'yes_no',why:'Protective clothing and hair covering help prevent contamination of food.',what:['Check clean work clothing, apron and required head covering.','Replace visibly dirty protective clothing.'],standard:'Suitable protective clothing and headgear should be used where necessary.',risk:'Hair, dirt or contaminants can enter food.',action:'Replace or correct the protective clothing before food handling continues.'},
 {id:8,code:'FS28-08',category:'Personal hygiene',title:'Food handlers who should not handle food are kept away',frequency:'Per shift',input:'yes_no',why:'Illness or uncovered wounds can create a contamination risk.',what:['Follow the restaurant procedure for reporting illness or wounds.','Do not allow affected staff to handle exposed food when they should be excluded.'],standard:'Food handlers with relevant illness, open wounds or burns should be managed according to the applicable food-safety procedure.',risk:'Contamination may be transferred to food.',action:'Remove the food-handling assignment and inform the responsible manager.'},
 {id:9,code:'FS28-09',category:'Personal hygiene',title:'Unsafe behaviour is absent during food handling',frequency:'Per shift',input:'yes_no',why:'Eating, smoking, spitting and similar behaviour can contaminate food and food areas.',what:['Observe food-handling areas for unsafe behaviour.','Check that the workplace rules are followed.'],standard:'Food handlers should maintain good hygiene behaviour and avoid practices that can contaminate food.',risk:'Direct contamination of food or surfaces can occur.',action:'Stop the behaviour immediately and reinforce the relevant hygiene rule.'},
 {id:10,code:'FS28-10',category:'Receiving & storage',title:'Incoming food is checked before acceptance',frequency:'Daily',input:'yes_no',why:'Problems can be prevented from entering the kitchen when food is checked at receipt.',what:['Check condition, packaging, date information and temperature where applicable.','Reject or isolate unsuitable food according to the restaurant procedure.'],standard:'Incoming food should be checked and protected from contamination before acceptance.',risk:'Spoiled, damaged or temperature-abused food may enter the operation.',action:'Do not accept unsuitable food; record and escalate repeated supplier problems.'},
 {id:11,code:'FS28-11',category:'Receiving & storage',title:'Raw and ready-to-eat food are kept separate',frequency:'Daily',input:'yes_no',why:'Separation reduces cross-contamination between raw foods and foods that will not receive further cooking.',what:['Check storage shelves, containers and preparation areas.','Keep raw animal foods separated from ready-to-eat foods.'],standard:'Raw and ready-to-eat food should be appropriately segregated and protected.',risk:'Microorganisms from raw food can contaminate ready-to-eat food.',action:'Separate the foods, clean affected surfaces and correct the storage arrangement.'},
 {id:12,code:'FS28-12',category:'Receiving & storage',title:'Food is stored off the floor and protected',frequency:'Daily',input:'yes_no',why:'Protected storage reduces contamination from dirt, water, pests and handling.',what:['Check that food is not stored directly on the floor.','Check containers, covers and packaging for protection.'],standard:'Food should be stored hygienically, protected from contamination and off the floor where applicable.',risk:'Floor-level storage increases exposure to contamination and pests.',action:'Move food to suitable storage and discard/assess any contaminated stock.'},
 {id:13,code:'FS28-13',category:'Receiving & storage',title:'FIFO (First In, First Out) / FEFO (First Expiry, First Out) is followed',frequency:'Daily',input:'yes_no',why:'Using older or earlier-expiring stock first reduces avoidable spoilage and waste.',what:['Check dates and stock arrangement.','Place earlier-expiring items where they will be used first.'],standard:'FIFO/FEFO should be followed as applicable to the stock.',risk:'Expired or deteriorated food may be used.',action:'Re-arrange stock and remove expired/unsafe items according to procedure.'},
 {id:14,code:'FS28-14',category:'Receiving & storage',title:'Cool Room and Cold Room temperatures are maintained within the required range',frequency:'Daily',input:'temperature',why:'Temperature control slows or prevents growth of harmful microorganisms and protects food quality.',what:['Measure the relevant refrigerator/freezer temperature.','Check door closure, loading and air circulation.'],standard:'Cool Room: 4°C or below. Cold Room: −18°C or below where applicable. Apply any stricter configured food/process requirement.',risk:'Prolonged temperature abuse can allow microbial growth or deterioration.',action:'Protect/isolate affected food, correct the temperature problem and escalate repeated deviations.'},
 {id:15,code:'FS28-15',category:'Food preparation & cross-contamination',title:'Raw materials are appropriately cleaned before preparation',frequency:'Process',input:'yes_no',why:'Appropriate cleaning can remove soil and other contaminants before food preparation.',what:['Follow the approved preparation method for the ingredient.','Do not use unsafe washing practices that introduce contamination.'],standard:'Raw materials should be handled and cleaned according to the applicable food process.',risk:'Contaminants may remain or spread to other foods/surfaces.',action:'Repeat the approved preparation step and clean affected surfaces.'},
 {id:16,code:'FS28-16',category:'Food preparation & cross-contamination',title:'Raw and cooked/ready-to-eat food are handled separately',frequency:'Process',input:'yes_no',why:'Separate handling reduces transfer of contamination after cooking.',what:['Use appropriate utensils, boards and work areas.','Clean hands and surfaces between incompatible tasks.'],standard:'Food should be prepared hygienically with appropriate segregation and protection from contamination.',risk:'Ready-to-eat food can be contaminated after cooking.',action:'Stop the cross-contamination, clean/sanitise as required and assess affected food.'},
 {id:17,code:'FS28-17',category:'Food preparation & cross-contamination',title:'Food-contact equipment and utensils are clean and sanitised',frequency:'Daily',input:'yes_no',why:'Utensils and equipment directly contact food and can transfer contamination.',what:['Check knives, boards, utensils, counters and relevant equipment.','Follow the restaurant cleaning and sanitising procedure.'],standard:'Food-contact equipment and utensils should be cleaned hygienically and sanitised where required.',risk:'Contaminated equipment can repeatedly transfer microorganisms to food.',action:'Remove from use, clean/sanitise correctly and re-check.'},
 {id:18,code:'FS28-18',category:'Food preparation & cross-contamination',title:'Food is protected during preparation and portioning',frequency:'Process',input:'yes_no',why:'Exposed food can be contaminated during handling and waiting periods.',what:['Keep food covered/protected when not actively being handled.','Use clean utensils and minimise unnecessary exposure.'],standard:'Food should be protected from contamination during preparation and handling.',risk:'Dust, droplets, hands, pests or contaminated equipment can contaminate exposed food.',action:'Cover/protect food and discard or assess any food that has been contaminated.'},
 {id:19,code:'FS28-19',category:'Temperature control',title:'Cold-storage temperature is checked',frequency:'Daily',input:'temperature',why:'Checking temperature makes temperature abuse visible before unsafe food remains in storage unnoticed.',what:['Read the refrigerator temperature with the working monitoring device.','Record the actual reading and check food placement/door closure.'],standard:'Operational reference: chilled foods 5°C or below; use the applicable product/process requirement configured for the outlet.',risk:'An unnoticed rise in temperature can allow microbial growth.',action:'Re-check with an independent thermometer, protect affected food and create an issue if the condition is not corrected.'},
 {id:20,code:'FS28-20',category:'Temperature control',title:'Frozen-storage temperature is checked',frequency:'Daily',input:'temperature',why:'Frozen storage must remain cold enough to protect frozen food quality and safety.',what:['Measure the freezer temperature.','Check for overloading, ice build-up and poor door closure.'],standard:'Operational reference: frozen products −18°C or below where applicable.',risk:'Temperature rise can cause thawing, quality loss and potential safety concerns depending on the food and duration.',action:'Protect affected food, restore temperature and escalate repeated equipment problems.'},
 {id:21,code:'FS28-21',category:'Temperature control',title:'Cooking or reheating temperature is checked where applicable',frequency:'Process',input:'temperature',why:'Adequate cooking is an important control for reducing food-safety hazards.',what:['Choose whether you are checking cooking or reheating.','Use a clean thermometer probe in the food core and record the actual temperature and required time.'],standard:'Cooking: use the applicable FSSAI food-specific time/temperature option shown on screen. Reheating: core temperature 75°C or above for at least 2 minutes, using the approved direct reheating method where applicable.',risk:'Insufficient cooking may allow harmful microorganisms to survive.',action:'Continue cooking to the validated requirement and re-check before service.'},
 {id:22,code:'FS28-22',category:'Temperature control',title:'Cooked food is cooled safely',frequency:'Process',input:'temperature',why:'Rapid cooling limits the time cooked high-risk food spends at temperatures that support microbial growth.',what:['Record the first cooling checkpoint and how long it took to reach it.','Record the final cooling checkpoint and the time taken from the first checkpoint.'],standard:'FSSAI operational reference: cool high-risk cooked food from 60°C to 21°C within 2 hours or less, then to 5°C within a further 2 hours or less, where applicable.',risk:'Slow cooling can allow microorganisms to multiply.',action:'Apply the approved rapid-cooling method and assess food that has exceeded the permitted process limit.'},
 {id:23,code:'FS28-23',category:'Temperature control',title:'Hot/cold holding is checked',frequency:'Per shift',input:'temperature',why:'Holding food at the required temperature reduces the time it spends in conditions that support microbial growth.',what:['Choose hot or cold holding and, for hot holding, choose vegetarian or non-vegetarian food.','Measure the food temperature at the holding point and record the actual reading.'],standard:'Hot holding: vegetarian food ≥65°C; non-vegetarian food ≥70°C. Cold holding: ≤5°C. Apply any stricter configured product/process requirement.',risk:'Poor holding control can allow microbial growth before service.',action:'Restore the holding condition, re-check and assess affected food according to the outlet procedure.'},
 {id:24,code:'FS28-24',category:'Cleaning, pests & waste',title:'Cleaning schedule is completed',frequency:'Daily',input:'yes_no',why:'Routine cleaning removes food residues and contamination from the environment.',what:['Check the scheduled cleaning tasks for the day.','Pay attention to food-contact surfaces, equipment, floors and difficult areas.'],standard:'Cleaning should follow the restaurant’s documented cleaning programme.',risk:'Missed cleaning allows residues and contamination to accumulate.',action:'Complete the missed task and record the correction.'},
 {id:25,code:'FS28-25',category:'Cleaning, pests & waste',title:'Food-contact surfaces are clean and sanitised',frequency:'Daily',input:'yes_no',why:'Food-contact surfaces can transfer contamination directly to food.',what:['Inspect counters, boards, utensils and other food-contact surfaces.','Check that sanitising is done according to the approved method.'],standard:'Food-contact surfaces should be clean and sanitised where required by the process.',risk:'Residual contamination can be transferred to food.',action:'Remove the surface from use, clean/sanitise and verify before reuse.'},
 {id:26,code:'FS28-26',category:'Cleaning, pests & waste',title:'No evidence of pest activity',frequency:'Opening',input:'yes_no',why:'Pests can contaminate food, equipment and food-contact surfaces.',what:['Look for live/dead pests, droppings, eggs, larvae, gnaw marks or other signs.','Check corners, drains, storage areas and waste areas.'],standard:'There should be no signs of pest activity in food-handling areas.',risk:'Pest activity can contaminate food and indicates that the underlying control needs attention.',action:'Protect food, report the finding and activate the pest-control procedure; do not treat a pesticide application as a substitute for cleaning and exclusion.'},
 {id:27,code:'FS28-27',category:'Cleaning, pests & waste',title:'Pest-control measures are in place',frequency:'Daily',input:'yes_no',why:'Pest prevention works best when access, food, water and shelter are controlled continuously.',what:['Check that approved traps/barriers are present where required.','Check that pest-control actions or service visits are up to date according to the programme.'],standard:'A suitable pest-control programme should be maintained for the food premises.',risk:'Gaps in prevention can allow an infestation to develop.',action:'Restore the control and escalate to the responsible pest-control/management process.'},
 {id:28,code:'FS28-28',category:'Cleaning, pests & waste',title:'Food waste is removed and the waste area is controlled',frequency:'Daily',input:'yes_no',why:'Food waste provides food, moisture and shelter that can attract pests and create hygiene problems.',what:['Check bins and waste areas for overflow, leaks or exposed food waste.','Ensure waste is removed at the required frequency and the area is kept clean.'],standard:'Food waste and refuse should be removed periodically to avoid accumulation and the waste area should be maintained hygienically.',risk:'Accumulated waste can attract pests and contaminate food areas.',action:'Remove waste, clean the affected area and report recurring waste-management problems.'}
];

export const DAILY_BADGE_RULES = { green:'All scheduled checks completed; no unresolved action-required issue.', yellow:'All scheduled checks may be completed, but one or more issues remain open or require attention.', red:'A critical food-safety issue remains unresolved or a required control has failed and has not been corrected/verified.' };
