'use client';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {ArrowRight, CheckCircle2, Thermometer} from 'lucide-react';
const data:any={
 storage:{title:'Storage',icon:'🧊',summary:'Keep chilled, frozen and stored foods at the right temperature and protected from contamination.',reference:'FSSAI Hygiene Rating references foods of animal origin at ≤4°C, cold foods at ≤5°C and frozen products at ≤−18°C. Storage should also maintain segregation and FIFO/FEFO, with food protected from contamination.',monitor:'Storage temperature + segregation + labelling + FIFO/FEFO',action:'Restore the correct storage condition, segregate or protect affected food, assess food safety and record/verify the corrective action.'},
 cooking:{title:'Cooking',icon:'🍳',summary:'Achieve the applicable food-specific cooking temperature and time.',reference:'FSSAI Hygiene Rating references vegetarian food at 60°C for 10 minutes or 65°C for 2 minutes core temperature. For non-vegetarian food, references are 65°C for 10 minutes, 70°C for 2 minutes or 75°C for 15 seconds core temperature.',monitor:'Core temperature + time',action:'If the approved cooking control is not achieved, continue or otherwise follow the approved corrective process, protect the food and verify before release.'},
 cooling:{title:'Cooling',icon:'❄️',summary:'Cool high-risk cooked food quickly and safely before refrigeration.',reference:'FSSAI Hygiene Rating material references cooling high-risk food from 60°C to 21°C within 2 hours or less, then from 21°C to 5°C within a further 2 hours or less.',monitor:'Start temperature/time + 21°C time + 5°C time',action:'If the cooling process is outside the approved limit, protect the food, assess disposition and record/verify the corrective action.'},
 thawing:{title:'Thawing',icon:'💧',summary:'Thaw frozen food hygienically and prevent unsafe storage after thawing.',reference:'FSSAI Hygiene Rating references meat, fish and poultry thawing in a refrigerator at ≤5°C or in a microwave. Shellfish/seafood may be thawed in cold potable running water at ≤15°C within 90 minutes. No thawed food should be stored for later use.',monitor:'Thawing method + temperature + time',action:'Stop or correct an unsafe thawing method, protect the food, assess whether it is safe to use and record the decision.'},
 reheating:{title:'Reheating',icon:'↻',summary:'Reheat safely and uniformly before service.',reference:'FSSAI Hygiene Rating material references a core temperature of 75°C, maintained for at least 2 minutes, for reheating.',monitor:'Core temperature + time',action:'If the approved reheating control is not achieved, continue or otherwise follow the approved corrective process and verify before service.'},
};
export default function ControlDetail(){const p=useParams(); const c=data[String(p.control)]||data.storage; return <main><div className="container"><div className="breadcrumb"><Link href="/home">Home</Link> › <Link href="/temperature-controls">Temperature Controls</Link> › {c.title}</div><div className="control-hero"><div className="control-icon large">{c.icon}</div><div><p className="eyebrow">TEMPERATURE CONTROL</p><h1>{c.title}</h1><p className="lead">{c.summary}</p></div></div><div className="grid grid2" style={{marginTop:24}}><div className="card"><h3>FSSAI reference</h3><p>{c.reference}</p><a href="https://hygiene.fssai.gov.in/" target="_blank" rel="noreferrer">Open FSSAI source</a></div><div className="card"><h3>What to monitor</h3><p>{c.monitor}</p></div></div><div className="card" style={{marginTop:20}}><h3>If there is a deviation</h3><p>{c.action}</p></div><div className="notice" style={{marginTop:20}}><CheckCircle2 size={20}/><div><strong>Simple workflow</strong><p style={{margin:'4px 0 0'}}>Check → Measure → FoodSafe365 evaluates the result → Correct if needed → Verify → Record.</p></div></div><div className="section-title"><div><p className="eyebrow">NEXT STEP</p><h2>Ready to check {c.title.toLowerCase()}?</h2><p className="muted">This starts a focused check. It will not take you through unrelated daily checks.</p></div><Link href={`/checks?focus=${String(p.control)}`} className="btn primary">Check {c.title} Now <ArrowRight size={17}/></Link></div></div></main>}
