'use client';
import Link from 'next/link';
import { ArrowRight, BookOpen, CheckCircle2, ChevronLeft, ShieldCheck } from 'lucide-react';
import { FOODSAFE28 } from '@/lib/foodsafety28';
export default function Checklist(){
 const groups=Array.from(new Set(FOODSAFE28.map(x=>x.category)));
 return <main><div className="topbar"><div className="brand">FoodSafe365</div><div className="muted">Supervisor · Food safety controls</div></div><div className="container manager-shell">
  <Link href="/home" className="nav-link muted back-row"><ChevronLeft size={17}/> Home</Link>
  <div className="page-title"><p className="eyebrow">FOODSAFE365 DAILY FOOD SAFETY CHECK</p><h1>28-point operational checklist</h1><p className="lead">A practical daily control library derived from applicable FSSAI food-service hygiene requirements. It is not an official FSSAI “28-point” checklist.</p></div>
  <div className="grid grid2 education-links">
   <Link href="/food-safety-why" className="card link-card"><ShieldCheck/><div><p className="eyebrow">LEARN FIRST</p><h2>Food Safety — Why?</h2><p className="muted">Understand why the supervisor checks these controls and how a missed control can affect food safety.</p></div><ArrowRight/></Link>
   <Link href="/food-safety-framework" className="card link-card"><BookOpen/><div><p className="eyebrow">UNDERSTAND THE SYSTEM</p><h2>Food Safety Framework</h2><p className="muted">See how the 28-point controls, temperature controls and HACCP fit together.</p></div><ArrowRight/></Link>
  </div>
  <div className="card badge-preview"><div className="badge-icon"><CheckCircle2/></div><div><p className="eyebrow">END-OF-DAY OUTPUT</p><h2>FoodSafe365 Daily Food Safety Badge</h2><p className="muted">The badge will be based on actual completed checks and real unresolved issues—not an arbitrary score.</p></div><Link className="btn primary" href="/checks">Start today’s checks <ArrowRight size={17}/></Link></div>
  {groups.map(g=><section key={g} className="section-block"><div className="section-title"><div><h2>{g}</h2><p className="muted">{FOODSAFE28.filter(x=>x.category===g).length} controls</p></div></div><div className="checklist-library">{FOODSAFE28.filter(x=>x.category===g).map(x=><Link href={`/checks?check=${x.id}`} key={x.id} className="card library-row"><div className="library-number">{x.id}</div><div className="library-main"><h3>{x.title}</h3><p className="muted">{x.frequency} · {x.input==='temperature'?'Temperature':'Observation'}</p></div><ArrowRight size={18}/></Link>)}</div></section>)}
  <div className="card source-note"><BookOpen size={19}/><div><strong>Source note</strong><p className="muted">FoodSafe365 should retain the exact FSSAI source/version applicable to each control when this moves beyond Phase 1. Some controls are process-based or periodic rather than literally daily; the supervisor’s “Today” list should therefore be generated by frequency and outlet applicability.</p></div></div>
 </div></main>;
}
