'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, CheckCircle2, ChevronLeft, ShieldCheck, Wrench } from 'lucide-react';
import { useParams } from 'next/navigation';
const key='foodsaf365_phase1';
function load(){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
function save(v:any){localStorage.setItem(key,JSON.stringify(v));window.dispatchEvent(new Event('foodsaf365:update'));}
function label(s:string){return s==='awaiting_verification'?'Awaiting verification':s==='in_progress'?'In progress':s==='closed'?'Closed':'Open'}
export default function ActionDetail(){const params=useParams<{action_id:string}>();const [d,setD]=useState<any>({});const [a,setA]=useState<any>(null);const [immediate,setImmediate]=useState('');const [corrective,setCorrective]=useState('');const [root,setRoot]=useState('');const [note,setNote]=useState('');const [message,setMessage]=useState('');useEffect(()=>{const r=()=>{const x=load();setD(x);setA((x.actions||[]).find((z:any)=>z.id===params.action_id)||null)};r();window.addEventListener('foodsaf365:update',r);return()=>window.removeEventListener('foodsaf365:update',r)},[params.action_id]);useEffect(()=>{if(a){setImmediate(a.immediateAction||'');setCorrective(a.correctiveAction||'');setRoot(a.rootCause||'');setNote(a.verificationNote||'')}},[a?.id]);if(!a)return <main><div className="container"><p className="muted">Action not found.</p><Link href="/actions" className="nav-link">Back to actions</Link></div></main>;
 function update(p:any){const actions=(d.actions||[]).map((x:any)=>x.id===a.id?{...x,...p}:x);const next={...d,actions};save(next);setD(next);setA(actions.find((x:any)=>x.id===a.id));}
 function submitAction(){if(!immediate.trim()&&!corrective.trim())return;const next={...d,actions:(d.actions||[]).map((x:any)=>x.id===a.id?{...x,immediateAction:immediate,correctiveAction:corrective,rootCause:root,status:'awaiting_verification',completedAt:new Date().toISOString()}:x),issues:(d.issues||[]).map((i:any)=>i.actionId===a.id?{...i,status:'awaiting_verification'}:i)};save(next);setD(next);setA((next.actions||[]).find((x:any)=>x.id===a.id));setMessage('Action submitted for manager verification.');}
 function verify(result:'pass'|'fail'){const now=new Date().toISOString();if(result==='pass'){const next={...d,actions:(d.actions||[]).map((x:any)=>x.id===a.id?{...x,status:'closed',verificationStatus:'pass',verificationNote:note,closedAt:now}:x),issues:(d.issues||[]).map((i:any)=>i.actionId===a.id?{...i,status:'closed',verifiedAt:now}:i)};save(next);setD(next);setA((next.actions||[]).find((x:any)=>x.id===a.id));setMessage('Correction verified. Issue closed.');}else{const next={...d,actions:(d.actions||[]).map((x:any)=>x.id===a.id?{...x,status:'in_progress',verificationStatus:'fail',verificationNote:note}:x),issues:(d.issues||[]).map((i:any)=>i.actionId===a.id?{...i,status:'action_in_progress'}:i)};save(next);setD(next);setA((next.actions||[]).find((x:any)=>x.id===a.id));setMessage('Verification failed. Action has been reopened.');}}
 const editable=['open','in_progress'].includes(a.status);return <main><div className="topbar"><div className="brand">FoodSafe365</div><div className="muted">ABC Restaurant · Corrective action</div></div><div className="container"><div className="checks-nav"><Link href="/actions" className="muted nav-link"><ChevronLeft size={18}/> Restaurant actions</Link></div><div className="checks-header"><div><p className="eyebrow">CORRECTIVE ACTION</p><h1>{a.title}</h1><p className="muted">Complete the correction, then submit it for manager verification.</p></div><div className="check-progress-box"><strong>{label(a.status).toUpperCase()}</strong><span className="muted">status</span></div></div>{message&&<div className="notice good-notice"><CheckCircle2 size={18}/>{message}</div>}<div className="card action-detail-status"><div className="icon-tile danger"><Wrench/></div><div><span className="eyebrow">WHY THIS ACTION EXISTS</span><h2>Manager-reviewed food-safety alert</h2><p className="muted">{a.description}</p></div></div><div className="grid grid2"><div className="card"><h2>1. What was done?</h2><label className="field"><span>Immediate action</span><textarea className="input textarea" value={immediate} onChange={e=>setImmediate(e.target.value)} disabled={!editable} placeholder="What did the restaurant do immediately?"></textarea></label><label className="field"><span>Corrective action</span><textarea className="input textarea" value={corrective} onChange={e=>setCorrective(e.target.value)} disabled={!editable} placeholder="What was corrected to restore the control?"></textarea></label><label className="field"><span>Root cause (optional)</span><textarea className="input textarea" value={root} onChange={e=>setRoot(e.target.value)} disabled={!editable} placeholder="Why did the problem happen?"></textarea></label>{editable&&<button className="btn primary" onClick={submitAction}>Submit for verification <ShieldCheck size={17}/></button>}</div><div className="card"><h2>2. Manager verification</h2><p className="muted">The manager verifies that the correction is effective before the alert is closed.</p><label className="field"><span>Verification note</span><textarea className="input textarea" value={note} onChange={e=>setNote(e.target.value)} disabled={a.status!=='awaiting_verification'} placeholder="What did the manager check?"></textarea></label>{a.status==='awaiting_verification'&&<div className="verification-grid"><button className="answer good-answer" onClick={()=>verify('pass')}><CheckCircle2/><span>Verified</span><small>Control restored</small></button><button className="answer issue-answer" onClick={()=>verify('fail')}><AlertTriangle/><span>Not verified</span><small>Reopen action</small></button></div>}{a.status==='closed'&&<div className="notice good-notice"><CheckCircle2 size={18}/> Verified and closed.</div>}</div></div></div></main>}
